# Generated by Django 2.0 on 2018-10-26 14:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AritcleDatils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=50000, null=True, verbose_name='文章内容')),
                ('LastDataChange', models.DateTimeField(default=datetime.datetime, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '文章详情',
                'verbose_name_plural': '文章详情',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ArticleName', models.CharField(max_length=50, verbose_name='文章名')),
                ('BackgroundPath', models.CharField(max_length=100, verbose_name='文章背景地址')),
                ('PostedTime', models.DateTimeField(default=datetime.datetime, verbose_name='发表时间')),
                ('Hits', models.IntegerField(verbose_name='点击数')),
                ('Likenum', models.IntegerField(verbose_name='点赞数')),
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='CategoryLog',
            field=models.CharField(max_length=100, null=True, verbose_name='Log地址'),
        ),
        migrations.AddField(
            model_name='article',
            name='CategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='外键类名id'),
        ),
        migrations.AddField(
            model_name='aritcledatils',
            name='ArticleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='外键文章id'),
        ),
    ]
