# Generated by Django 2.0 on 2018-11-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181105_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='BackgroundPath',
            field=models.CharField(max_length=50, verbose_name='背景地址'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryLog',
            field=models.CharField(max_length=50, null=True, verbose_name='Log地址'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryName',
            field=models.CharField(max_length=20, verbose_name='分类名'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Intor',
            field=models.CharField(max_length=100, null=True, verbose_name='分类详情'),
        ),
    ]
