# Generated by Django 2.0 on 2018-10-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181026_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ArticleSuggests',
            field=models.CharField(max_length=300, null=True, verbose_name='文章简述'),
        ),
    ]
