# Generated by Django 2.0 on 2018-11-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181106_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Intor',
            field=models.CharField(max_length=200, null=True, verbose_name='分类详情'),
        ),
    ]
