# Generated by Django 2.0 on 2018-11-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181106_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ArticleSuggests',
            field=models.CharField(max_length=200, null=True, verbose_name='文章详情'),
        ),
    ]
