# Generated by Django 2.0 on 2018-11-06 15:38

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_articlesuggests'),
    ]

    operations = [
        migrations.AddField(
            model_name='aritcledatils',
            name='Content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='开始一篇新的文章', max_length=102400, verbose_name='文章内容'),
        ),
    ]
