# Generated by Django 2.0 on 2018-11-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_aritcledatils_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ArticleName',
            field=models.CharField(max_length=300, verbose_name='文章名'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleSuggests',
            field=models.CharField(max_length=300, null=True, verbose_name='文章详情'),
        ),
        migrations.AlterField(
            model_name='article',
            name='BackgroundPath',
            field=models.ImageField(max_length=255, null=True, upload_to='article_img', verbose_name='文章背景地址'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Hits',
            field=models.IntegerField(default=1, verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Likenum',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='category',
            name='BackgroundPath',
            field=models.ImageField(max_length=255, null=True, upload_to='category_img', verbose_name='背景地址'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryLog',
            field=models.ImageField(max_length=255, null=True, upload_to='log_img', verbose_name='Log地址'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryName',
            field=models.CharField(max_length=50, verbose_name='分类名'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Intor',
            field=models.CharField(max_length=500, null=True, verbose_name='分类详情'),
        ),
    ]
