# Generated by Django 2.0 on 2018-10-31 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181031_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aritcledatils',
            name='LastDataChange',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='PostedTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间'),
        ),
    ]
