# Generated by Django 2.0 on 2018-11-04 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181031_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ArticleSuggests',
        ),
    ]
