# Generated by Django 2.0 on 2018-11-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181120_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='BackgroundPath',
            field=models.ImageField(max_length=255, null=True, upload_to='./article_img', verbose_name='文章背景地址'),
        ),
        migrations.AlterField(
            model_name='category',
            name='BackgroundPath',
            field=models.ImageField(max_length=255, null=True, upload_to='./category_img', verbose_name='背景地址'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryLog',
            field=models.ImageField(max_length=255, null=True, upload_to='./log_img', verbose_name='Log地址'),
        ),
    ]
