# Generated by Django 2.0 on 2018-12-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181120_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=300, verbose_name='用户id')),
                ('Type', models.IntegerField(default=1, verbose_name='行为类型类型,1喜欢')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='BackgroundPath',
            field=models.ImageField(max_length=255, null=True, upload_to='images/article_img', verbose_name='文章背景地址'),
        ),
        migrations.AlterField(
            model_name='category',
            name='BackgroundPath',
            field=models.ImageField(max_length=255, null=True, upload_to='images/category_back', verbose_name='背景地址'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryLog',
            field=models.ImageField(max_length=255, null=True, upload_to='images/category_log', verbose_name='Log地址'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='ArticleId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='外键文章id'),
        ),
    ]
