# Generated by Django 2.0 on 2018-12-08 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181206_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('UserName', models.CharField(max_length=300, verbose_name='用户姓名')),
                ('UserEmail', models.EmailField(max_length=254, null=True, verbose_name='用户Email')),
                ('Content', models.CharField(max_length=5000, verbose_name='评论内容')),
                ('PostedTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('Likenum', models.IntegerField(default=0, verbose_name='点赞数')),
                ('ArticleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='外键文章id')),
            ],
            options={
                'verbose_name': '评论',
            },
        ),
        migrations.AlterModelOptions(
            name='userbehavior',
            options={'verbose_name': '用户行为'},
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='Type',
            field=models.IntegerField(default=1, verbose_name='行为类型类型,1喜欢,2评论,3评论点赞'),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='CommentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='外键评论id'),
        ),
    ]
