# Generated by Django 2.0 on 2018-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181208_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='UserHeader',
            field=models.CharField(default='/static/images/CommentHeader.jpg', max_length=300, null=True, verbose_name='评论用户头像'),
        ),
    ]
