# Generated by Django 2.0 on 2018-12-11 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_userheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavior',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='行为时间'),
        ),
    ]
