# Generated by Django 2.0 on 2019-01-27 13:29

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20181211_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Hidden',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
        migrations.AlterField(
            model_name='aritcledatils',
            name='Content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
