# Generated by Django 2.0 on 2019-02-25 18:24

import datetime
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190127_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Content',
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='LastDataChange',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最后修改时间'),
        ),
    ]
